chore/adds-navbar
rendercon/RenderconKe2023Web pull request #26
Opened 2024-08-20 21:48 UTC by wangui-wamutitu

Adds navbar section

![Screenshot 2024-08-21 at 00 47 53](https://github.com/user-attachments/assets/b950d34a-ab02-434a-b3d0-bd46c010f791)

2024-08-21 14:09 UTC, cindykandie requested changes
I really like the rendercon logo addition that quite brilliant.

2024-08-22 08:34 UTC, wangui-wamutitu commented on src/app/components/Navbar.tsx
> +        <li><Link href="#speakers">Speakers</Link></li>
Is there an about section/page? I can't see one

2024-08-22 08:35 UTC, wangui-wamutitu commented on src/app/components/Navbar.tsx
> +
On it

2024-08-22 10:00 UTC, wangui-wamutitu commented on src/app/components/Navbar.tsx
> +
@cindykandie, responsiveness for small screens done

![Screenshot 2024-08-22 at 12 56 48](https://github.com/user-attachments/assets/370ae970-0ffc-47ea-a9ed-d0be9287d8b9)
![Screenshot 2024-08-22 at 12 56 57](https://github.com/user-attachments/assets/2b860eed-fabe-46a5-81c1-6a4b64baf11b)

2024-08-22 13:19 UTC, cindykandie requested changes
Hey Tish, let's comment out/leave out about and agenda navigators so we can add them after the pages are created.

You can rebase with the main branch and re-request review for merging

2024-08-22 13:19 UTC, cindykandie commented on src/app/components/Navbar.tsx
> +        <li><Link href="#">Agenda</Link></li>
hey, let's comment out/leave out about and agenda so we can add them after the pages are created.

2024-08-22 14:04 UTC, cindykandie approved these changes

2024-08-22 14:04 UTC, merged